arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD/s390x/test/openjdk-11"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/s390x/openjdk-11"
    - REPO="quay.io/ibmz/maven"
    - TAG="$REPO:3.6.3"
before_script: 
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
  - cd $TEST_DIR && bash $TEST_SCRIPT 
after_script:
  - docker push $REPO
